(()=>{'use strict';
const $=s=>document.querySelector(s),params=new URLSearchParams(location.search),hostMode=params.get('host')==='1',room=(params.get('room')||'').trim();
// ---------------------------------------------------------------------------
// Network configuration. index.html defines window.CHICKEN_HORDE_CONFIG; ?relay=wss://… overrides it.
// ---------------------------------------------------------------------------
const CFG=Object.assign({relayUrl:'',iceServers:null,peerPrefix:'chhorde-',p2pTimeout:4500},window.CHICKEN_HORDE_CONFIG||{});
if(params.get('relay'))CFG.relayUrl=params.get('relay');
function relayUrl(){let u=String(CFG.relayUrl||'').trim();if(!u)return '';if(u==='same-origin')u=location.origin;return u.replace(/^http(s?):/i,'ws$1:')}
function peerOptions(){const o={debug:0};if(CFG.iceServers)o.config={iceServers:CFG.iceServers};return o}
class Emitter{constructor(){this.h={}}on(t,f){(this.h[t]=this.h[t]||[]).push(f);return this}emit(t,...a){for(const f of this.h[t]||[])try{f(...a)}catch(e){console.error(e)}}}
if(hostMode){$('#host').classList.remove('hidden');import('./renderer3d.mjs?v=7.0.0').then(({createGameRenderer})=>initHost(createGameRenderer)).catch(error=>{console.error(error);$('#assetLoadStatus').textContent='No se pudo iniciar el renderizado 3D. Revisa la conexión y recarga.';$('#startBtn').disabled=true})}else if(room){$('#controller').classList.remove('hidden');initController(room)}else $('#landing').classList.remove('hidden');

function initHost(createGameRenderer){
 let timeShift=0,paused=false,godMode=false;const clock=()=>performance.now()+timeShift;
 const canvas=$('#game'),lobby=$('#lobby'),roster=$('#roster'),players=new Map();let started=false,gameOver=false,wave=0,farmHp=100,shots=[],enemyBeams=[],fireballs=[],enemies=[],drops=[],last=performance.now(),spawn=0,remainingToSpawn=0,elitesToSpawn=[],spawnGroups=[],tornadoesThisWave=0,countdown=0,audio=null,soundOn=false,lastShotSound=0,henLastHit=0,lastHenCry=0,bloodSplats=[],musicOn=false,musicStarted=false,laserWave=0,waveGroups=0,waveElites=0,fx=[],fxId=0,dropId=0;const reconnectGrace=45000,kickedIds=new Set();
 const turret={active:false,angle:Math.PI/2,lastShot:0,target:null,shotAt:0};
 const world={w:1800,h:1200,home:{x:900,y:650}};const assetStatus=$('#assetLoadStatus'),startButton=$('#startBtn'),obstacleCell=240,obstacleGrid=new Map();startButton.disabled=true;assetStatus.textContent='Precargando modelos 3D en el lobby…';
 // ---------------------------------------------------------------------------
 // Map layout. Trees and rocks block movement and projectiles. Fences, hay bales
 // and logs are LOW cover: they block movement (so they funnel the horde through
 // gaps) but bullets fly over them, so players can shoot across.
 // ---------------------------------------------------------------------------
 const trees=[],decor=[],H=world.home;let fenceId=0;
 const addOb=o=>{trees.push(o);return o};
 const free=(x,y,r)=>x>r+40&&y>r+40&&x<world.w-r-40&&y<world.h-r-40&&!trees.some(t=>Math.hypot(t.x-x,t.y-y)<t.radius+r+12);
 function fence(cx,cy,angle,len){const id=fenceId++,n=Math.max(2,Math.round(len/24));for(let i=0;i<=n;i++){const f=i/n-.5;addOb({kind:'fence',x:cx+Math.cos(angle)*len*f,y:cy+Math.sin(angle)*len*f,radius:10,low:true,fenceId:id,idx:i,angle})}}
 function hayRow(cx,cy,angle,count){for(let i=0;i<count;i++){const f=i-(count-1)/2;addOb({kind:'hay',x:cx+Math.cos(angle)*f*44,y:cy+Math.sin(angle)*f*44,radius:21,low:true,angle})}}
 function log(cx,cy,angle){addOb({kind:'log',x:cx,y:cy,radius:16,low:true,angle,len:3});for(const f of [-1,1])addOb({kind:'logpart',x:cx+Math.cos(angle)*f*30,y:cy+Math.sin(angle)*f*30,radius:15,low:true})}
 function rock(x,y,r,cover=false){if(free(x,y,r))addOb({kind:'rock',x,y,radius:r,s:r*1.4,cover,seed:(x*7+y*13)%17})}
 function tree(x,y,s=1){if(free(x,y,14))addOb({kind:'tree',x,y,radius:14,s,seed:(x*3+y*11)%23,variant:Math.floor((x+y)/37)%3})}
 // Cover boulders right next to the henhouse.
 for(const [dx,dy] of [[-165,-130],[165,-130],[-165,135],[165,135]])rock(H.x+dx,H.y+dy,20,true);
 // Middle ring: hay walls on the diagonals and rock clusters east/west split the horde into lanes.
 for(const a of [Math.PI/4,3*Math.PI/4,5*Math.PI/4,7*Math.PI/4])hayRow(H.x+Math.cos(a)*500,H.y+Math.sin(a)*500*.82,a+Math.PI/2,3);
 for(const side of [-1,1]){const cx=H.x+side*585,cy=H.y-20;rock(cx,cy-70,26);rock(cx+side*22,cy+8,22);rock(cx-side*8,cy+82,24)}
 for(const [x,y,a] of [[H.x-260,H.y-470,.2],[H.x+270,H.y-460,-.25],[H.x-300,H.y+420,-.15],[H.x+310,H.y+410,.3]])log(x,y,a);
 // Outer groves at the corners plus scattered edge trees keep the borders readable without closing spawn edges.
 for(const [cx,cy] of [[190,190],[world.w-190,190],[190,world.h-170],[world.w-190,world.h-170]])for(let i=0;i<6;i++){const a=i*2.399+cx*.01,r=i?52+i*14:0;tree(cx+Math.cos(a)*r,cy+Math.sin(a)*r,.9+(i%3)*.18)}
 for(const [x,y] of [[520,150],[1280,140],[600,1070],[1210,1080],[120,560],[1680,600],[380,380],[1420,400],[400,880],[1410,860],[700,300],[1100,290]])tree(x,y,.85+((x+y)%5)*.08);
 for(const [x,y,r] of [[520,560,18],[1290,560,17],[760,980,16],[1050,990,18],[640,240,15],[1170,220,16]])rock(x,y,r);
 // Decorations (no collision).
 for(let i=0;i<70;i++){const x=(97+i*263)%world.w,y=(61+i*389)%world.h;if(Math.hypot(x-H.x,y-H.y)>200&&free(x,y,8))decor.push({kind:i%5===0?'pumpkin':i%3===0?'mushroom':'flowers',x,y,seed:i})}
 for(const [dx,dy] of [[-120,40],[120,40],[-95,-60],[105,-55]])decor.push({kind:'pumpkin',x:H.x+dx,y:H.y+dy,seed:dx+dy});
 const grassTufts=[];for(let i=0;i<420;i++){const x=(100+(i*617%3400))*.5,y=(100+(i*353%2200))*.5;if(Math.hypot(x-H.x,y-H.y)>175&&!trees.some(t=>Math.hypot(t.x-x,t.y-y)<t.radius+14))grassTufts.push({x,y,s:(34+(i*13%24))*.5,r:(i*1.71)%6.28})}
 for(const t of trees){const key=Math.floor(t.x/obstacleCell)+','+Math.floor(t.y/obstacleCell),bucket=obstacleGrid.get(key)||[];bucket.push(t);obstacleGrid.set(key,bucket)}
 const game3d=createGameRenderer({canvas,world,trees,decor,grassTufts,status:assetStatus,startButton});
 function send(p,force=false){const now=clock();if(!force&&now-(p.lastSend||0)<90)return;p.lastSend=now;try{if(p.conn?.open)p.conn.send({type:'state',started,hp:Math.ceil(p.hp),color:p.color,name:p.name,revive:+(p.revive||0).toFixed(2),laser:!!p.effects.LASER,wave})}catch{}}
 function rosterUpdate(){$('#playerCount').textContent=players.size;for(const target of [roster,$('#rosterInGame')]){target.innerHTML='';for(const p of players.values()){const e=document.createElement('div');e.className='roster-player'+(p.connected?'':' reconnecting');const avatar=document.createElement('span');avatar.className='roster-avatar';avatar.style.setProperty('--chick',p.color);avatar.textContent='🐥';const name=document.createElement('b');name.textContent=p.name;name.style.color=p.color;const status=document.createElement('small');status.textContent=p.connected?'READY · '+(p.via==='relay'?'RELAY':'P2P'):'RECONNECTING…';const kick=document.createElement('button');kick.className='kick-button';kick.textContent='KICK';kick.setAttribute('aria-label','Kick '+p.name);kick.onclick=()=>kickPlayer(p);e.append(avatar,name,status,kick);target.append(e)}}$('#lobbyEmpty')?.classList.toggle('hidden',players.size>0)}
 function kickPlayer(p){kickedIds.add(p.clientId);try{p.conn?.send({type:'kicked'})}catch{}try{p.conn?.close()}catch{}clearTimeout(p.expireTimer);players.delete(p.id);rosterUpdate();toast(p.name+' removed from the lobby')}
 function bindPlayer(conn,p){if(p.conn&&p.conn!==conn){try{p.conn.close()}catch{}}p.conn=conn;p.via=conn.relay?'relay':'p2p';p.connected=true;p.lastSeen=clock();clearTimeout(p.expireTimer);conn.on('data',d=>{if(p.conn!==conn)return;if(d&&d.type==='input'){p.lastSeen=clock();p.move=screenVectorToWorld(+d.move?.x||0,+d.move?.y||0);p.aim=screenAngleToWorld(+d.aim||0);p.fire=!!d.fire}else if(d&&d.type==='ping')p.lastSeen=clock()});conn.on('close',()=>{if(p.conn!==conn)return;p.connected=false;p.move={x:0,y:0};p.fire=false;rosterUpdate();p.expireTimer=setTimeout(()=>{if(!p.connected){players.delete(p.id);rosterUpdate()}},reconnectGrace);toast(p.name+' connection lost — waiting to reconnect')});rosterUpdate();send(p,true)}
 const scoreKey='chicken-horde-high-scores-v1';
 function readScores(){try{const v=JSON.parse(localStorage.getItem(scoreKey)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
 function renderScores(target){const list=readScores().sort((a,b)=>b.score-a.score).slice(0,10);target.innerHTML=list.length?'<table class="score-table"><thead><tr><th>#</th><th>PLAYER</th><th>BEST</th><th>WAVE</th></tr></thead><tbody>'+list.map((s,i)=>`<tr><td>${i+1}</td><td>${escapeText(s.name)}</td><td>${s.score}</td><td>${s.wave}</td></tr>`).join('')+'</tbody></table>':'<p class="empty-scores">No scores yet. Start a game!</p>'}
 function escapeText(s){const el=document.createElement('span');el.textContent=String(s);return el.innerHTML}
 function refreshScoreboards(){renderScores($('#lobbyScores'));renderScores($('#finalScores'))}
 function saveRun(){const scores=readScores();for(const p of players.values()){const key=p.name.trim().toUpperCase(),row=scores.find(s=>s.key===key);if(row){if(p.score>row.score){row.score=p.score;row.wave=wave}row.kills=Math.max(row.kills||0,p.kills)}else scores.push({key,name:p.name,score:p.score,wave,kills:p.kills})}scores.sort((a,b)=>b.score-a.score);try{localStorage.setItem(scoreKey,JSON.stringify(scores.slice(0,100)))}catch{}$('#runSummary').textContent=`The farm fell in wave ${wave}. Farm health: ${Math.ceil(farmHp)}%.`;$('#runScores').innerHTML='<table class="score-table"><thead><tr><th>PLAYER</th><th>SCORE</th><th>KILLS</th></tr></thead><tbody>'+[...players.values()].sort((a,b)=>b.score-a.score).map(p=>`<tr><td>${escapeText(p.name)}</td><td>${p.score}</td><td>${p.kills}</td></tr>`).join('')+'</tbody></table>';refreshScoreboards();$('#gameOver').classList.remove('hidden')}
 function screenVectorToWorld(x,y){return {x,y:y/.82}}
 function screenAngleToWorld(a){const v=screenVectorToWorld(Math.cos(a),Math.sin(a));return Math.atan2(v.y,v.x)}
 // Random, well separated chick colours: pick the hue farthest from the hues already in the flock.
 function hslHex(h,s,l){s/=100;l/=100;const k=n=>(n+h/30)%12,a=s*Math.min(l,1-l),f=n=>l-a*Math.max(-1,Math.min(k(n)-3,Math.min(9-k(n),1)));return '#'+[f(0),f(8),f(4)].map(v=>Math.round(v*255).toString(16).padStart(2,'0')).join('')}
 function choosePlayerColor(){const used=[...players.values()].map(p=>p.hue).filter(h=>h!=null);let best=Math.random()*360,bestD=-1;for(let i=0;i<36;i++){const h=Math.random()*360,d=used.length?Math.min(...used.map(u=>Math.min(Math.abs(u-h),360-Math.abs(u-h)))):360;if(d>bestD){bestD=d;best=h}}const s=72+Math.random()*18,l=56+Math.random()*8;return {hue:best,color:hslHex(best,s,l)}}
 function addPlayer(conn,msg){if(!msg||msg.type!=='join')return;const clientId=String(msg.clientId||conn.peer).slice(0,80);if(kickedIds.has(clientId)){try{conn.send({type:'kicked'})}catch{}try{conn.close()}catch{}return}let p=[...players.values()].find(v=>v.clientId===clientId);const name=String(msg.name||'CHICK').replace(/[\u0000-\u001f]/g,'').trim().slice(0,12)||'CHICK';if(!p){const n=players.size,c=choosePlayerColor();p={id:clientId,clientId,name,x:H.x-75+(n%4)*50,y:H.y+190+Math.floor(n/4)*38,aim:0,move:{x:0,y:0},fire:false,hp:100,effects:{},score:0,kills:0,lastHit:0,conn:null,connected:false,color:c.color,hue:c.hue,revive:0,joinedAt:clock()};players.set(p.id,p);if(!started)pushFx('join',p.x,p.y,{playerId:p.id})}else p.name=name;bindPlayer(conn,p)}
 // ---------------------------------------------------------------------------
 // Networking: PeerJS (WebRTC P2P) + WebSocket relay fallback. Both carry the same
 // messages; controllers use whichever connects first. The room code is created
 // here, so the lobby works even when the PeerJS signaling server is blocked.
 // ---------------------------------------------------------------------------
 let roomCode='',peer=null,relay=null;const net={p2p:'connecting',relay:relayUrl()?'connecting':'off'};
 function newCode(){const A='ABCDEFGHJKMNPQRSTUVWXYZ23456789',r=crypto.getRandomValues(new Uint8Array(5));let s='';for(const v of r)s+=A[v%A.length];return s}
 function onIncoming(conn){conn.on('data',d=>{if(d&&d.type==='join')addPlayer(conn,d)})}
 function updateNet(){const label=v=>({online:'✓ ONLINE',connecting:'…',reconnecting:'↻',blocked:'✕ BLOCKED',off:'— OFF'})[v]||v;const el=$('#netStatus');if(el){el.innerHTML=`<span class="net-${net.p2p}">P2P ${label(net.p2p)}</span><span class="net-${net.relay}">RELAY ${label(net.relay)}</span>`;el.title=net.relay==='off'?'Configure relayUrl in index.html to support restrictive networks/proxies.':''}const sig=net.p2p+net.relay;if(sig===updateNet.last)return;updateNet.last=sig;if(net.p2p==='blocked'&&net.relay!=='online')toast(net.relay==='off'?'P2P is blocked on this network — configure the relay server (see README).':'P2P blocked — waiting for relay…')}
 function updateJoinInfo(){const u=new URL(location.href);u.search='?room='+encodeURIComponent(roomCode)+(params.get('relay')?'&relay='+encodeURIComponent(params.get('relay')):'');u.hash='';$('#roomCode').textContent=roomCode;$('#joinUrl').textContent=u.href;let qr='';try{const q=window.qrcode(0,'M');q.addData(u.href);q.make();qr=q.createDataURL(8,2)}catch{qr='https://api.qrserver.com/v1/create-qr-code/?size=280x280&data='+encodeURIComponent(u.href)}$('#qr').src=qr;$('#qrLarge').src=qr;$('#joinQrBtn').disabled=false}
 function startPeer(){if(typeof Peer==='undefined'){net.p2p='blocked';updateNet();return}try{peer?.destroy()}catch{}const me=new Peer(CFG.peerPrefix+roomCode,peerOptions());peer=me;net.p2p='connecting';me.on('open',()=>{if(peer!==me)return;net.p2p='online';updateNet()});me.on('connection',onIncoming);me.on('disconnected',()=>{if(peer!==me||me.destroyed)return;net.p2p='reconnecting';updateNet();setTimeout(()=>{try{if(!me.destroyed)me.reconnect()}catch{}},1500)});me.on('error',e=>{if(peer!==me)return;if(e.type==='unavailable-id'){setupNetwork();return}if(['network','server-error','socket-error','socket-closed','browser-incompatible'].includes(e.type)){net.p2p='blocked';updateNet();setTimeout(()=>{if(peer===me&&net.p2p==='blocked'&&!me.destroyed){try{me.reconnect()}catch{startPeer()}}},15000)}})}
 function startRelay(){relay?.stop();const url=relayUrl();if(!url){net.relay='off';updateNet();return}let ws=null,stopped=false,delay=1000;const conns=new Map();
  function open(){if(stopped)return;try{ws=new WebSocket(url)}catch{net.relay='blocked';updateNet();return}const sock=ws;sock.onopen=()=>{delay=1000;sock.send(JSON.stringify({t:'host',room:roomCode}))};sock.onmessage=ev=>{let m;try{m=JSON.parse(ev.data)}catch{return}if(m.t==='hosted'){net.relay='online';updateNet()}else if(m.t==='open'){const c=new Emitter();c.relay=true;c.peer='relay-'+m.sid;c.open=true;c.send=d=>{if(c.open&&sock.readyState===1)sock.send(JSON.stringify({t:'d',sid:m.sid,d}))};c.close=()=>{if(!c.open)return;c.open=false;try{sock.send(JSON.stringify({t:'kick',sid:m.sid}))}catch{}conns.delete(m.sid);c.emit('close')};conns.set(m.sid,c);onIncoming(c)}else if(m.t==='d'){conns.get(m.sid)?.emit('data',m.d)}else if(m.t==='close'){const c=conns.get(m.sid);if(c){c.open=false;conns.delete(m.sid);c.emit('close')}}else if(m.t==='error'&&m.reason==='taken'){stopped=true;setupNetwork()}};sock.onclose=()=>{for(const c of conns.values()){c.open=false;c.emit('close')}conns.clear();if(stopped)return;net.relay='reconnecting';updateNet();setTimeout(open,delay);delay=Math.min(10000,delay*1.6)};sock.onerror=()=>{}}
  open();const keep=setInterval(()=>{if(ws?.readyState===1)ws.send('{"t":"ping"}')},20000);relay={stop(){stopped=true;clearInterval(keep);try{ws?.close()}catch{}}}}
 function setupNetwork(){roomCode=newCode();updateJoinInfo();startPeer();startRelay();updateNet()}
 setupNetwork();
 function startMatch(){if(started)return;startMusic();gameOver=false;$('#gameOver').classList.add('hidden');lobby.classList.add('hidden');$('#startBtn').disabled=true;$('#startBtn').textContent='MATCH IN PROGRESS';farmHp=100;wave=0;shots=[];enemyBeams=[];fireballs=[];enemies=[];drops=[];bloodSplats=[];fx=[];remainingToSpawn=0;laserWave=0;turret.active=false;turret.angle=Math.PI/2;for(const p of players.values()){p.hp=100;p.effects={};p.score=0;p.kills=0;p.revive=0;p.deathAt=0;p.move={x:0,y:0};p.fire=false;p.x=H.x-90+[...players.keys()].indexOf(p.id)%4*60+(Math.random()-.5)*20;p.y=H.y+190+(Math.random()-.5)*30;send(p,true)}startWave(1)}
 $('#startBtn').onclick=startMatch;$('#playAgain').onclick=()=>{gameOver=false;$('#gameOver').classList.add('hidden');lobby.classList.remove('hidden');$('#startBtn').disabled=false;$('#startBtn').textContent='START GAME';turret.active=false;drops=[];fx=[];for(const [i,p] of [...players.values()].entries()){p.hp=100;p.effects={};p.deathAt=0;p.revive=0;p.move={x:0,y:0};p.fire=false;p.x=H.x-75+(i%4)*50;p.y=H.y+190+Math.floor(i/4)*38;send(p,true)}rosterUpdate()};$('#joinQrBtn').onclick=()=>{const panel=$('#joinQrPanel'),show=panel.classList.toggle('open');$('#joinQrBtn').setAttribute('aria-expanded',String(show))};$('#playersBtn').onclick=()=>{const panel=$('#playersPanel'),show=panel.classList.toggle('open');$('#playersBtn').setAttribute('aria-expanded',String(show))};refreshScoreboards();rosterUpdate();
 let toastTimer=0;function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
 function pushFx(kind,x,y,extra={}){fx.push({id:++fxId,kind,x,y,at:clock(),...extra})}
 function tone(freq=440,duration=.1,type='sine',volume=.035){if(!soundOn||!audio)return;try{const o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(Math.min(.15,volume*2.2),now);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+duration)}catch{}}
 function sweep(f1,f2,duration=.3,type='sine',volume=.05){if(!soundOn||!audio)return;try{const now=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f1,now);o.frequency.exponentialRampToValueAtTime(f2,now+duration);g.gain.setValueAtTime(volume,now);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+duration+.02)}catch{}}
 function chickDeathSound(){if(!soundOn||!audio)return;try{const now=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(920,now);o.frequency.exponentialRampToValueAtTime(370,now+.18);o.frequency.exponentialRampToValueAtTime(160,now+.62);g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(.09,now+.04);g.gain.exponentialRampToValueAtTime(.001,now+.66);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+.67)}catch{}}
 function henCry(){if(!soundOn||!audio)return;try{const now=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type='sawtooth';o.frequency.setValueAtTime(720,now);o.frequency.exponentialRampToValueAtTime(1180,now+.08);o.frequency.exponentialRampToValueAtTime(560,now+.2);o.frequency.exponentialRampToValueAtTime(860,now+.28);o.frequency.exponentialRampToValueAtTime(430,now+.46);g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(.045,now+.035);g.gain.setValueAtTime(.04,now+.24);g.gain.exponentialRampToValueAtTime(.001,now+.48);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+.49)}catch{}}
 const bgMusic=$('#bgMusic'),musicVolume=$('#musicVolume');bgMusic.volume=.32;function setMusic(enabled){musicOn=enabled;$('#musicBtn').textContent=musicOn?'♫ MUSIC ON':'♫ MUSIC OFF';if(musicOn){musicStarted=true;const playing=bgMusic.play();if(playing?.catch)playing.catch(()=>toast('Tap MUSIC again if playback was blocked'))}else bgMusic.pause()}function startMusic(){if(!musicStarted)setMusic(true)}musicVolume.oninput=()=>{bgMusic.volume=Number(musicVolume.value)/100;$('#musicVolumeLabel').textContent=musicVolume.value+'%'};$('#musicBtn').onclick=()=>setMusic(!musicOn);$('#soundBtn').onclick=async()=>{soundOn=!soundOn;if(soundOn){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){soundOn=false;toast('Audio is not supported in this browser')}else{audio=audio||new Audio();if(audio.state==='suspended')await audio.resume()}}$('#soundBtn').textContent=soundOn?'SFX ON':'SFX OFF';tone(620,.12,'triangle')};
 // shot=true: low cover (fences, hay, logs) does not stop projectiles.
 function collidesTree(x,y,r,shot=false){const gx=Math.floor(x/obstacleCell),gy=Math.floor(y/obstacleCell),reach=Math.ceil((r+90)/obstacleCell);for(let cx=gx-reach;cx<=gx+reach;cx++)for(let cy=gy-reach;cy<=gy+reach;cy++)for(const t of obstacleGrid.get(cx+','+cy)||[]){if(shot&&t.low)continue;if(Math.hypot(x-t.x,y-t.y)<(t.radius||t.s)+r+(shot?0:6))return true}return false}
 function pathBlocked(x,y,nx,ny,r,shot=false){const steps=Math.max(1,Math.ceil(Math.hypot(nx-x,ny-y)/8));for(let i=1;i<=steps;i++){const f=i/steps;if(collidesTree(x+(nx-x)*f,y+(ny-y)*f,r,shot))return true}return false}
 function moveCircle(o,dx,dy,r){const count=Math.max(1,Math.ceil(Math.hypot(dx,dy)/8)),sx=dx/count,sy=dy/count;let x=o.x,y=o.y;for(let i=0;i<count;i++){const nx=Math.max(r,Math.min(world.w-r,x+sx));if(!collidesTree(nx,y,r))x=nx;const ny=Math.max(r,Math.min(world.h-r,y+sy));if(!collidesTree(x,ny,r))y=ny}return {x,y}}
 function findSpawnPosition(radius){for(let attempt=0;attempt<40;attempt++){const side=Math.floor(Math.random()*4),x=side===0?90:side===1?world.w-90:90+Math.random()*(world.w-180),y=side===2?90:side===3?world.h-90:90+Math.random()*(world.h-180);if(!collidesTree(x,y,radius))return {x,y}}return {x:H.x+650,y:H.y+450}}
 function moveEnemy(e,dx,dy,r){const clamp=(v,max)=>Math.max(r,Math.min(max-r,v)),x=clamp(e.x+dx,world.w),y=clamp(e.y+dy,world.h);if(!pathBlocked(e.x,e.y,x,y,r)){e.routeAngle=null;e.stuck=0;return {x,y}}const base=Math.atan2(dy,dx),turns=[0,-.42,.42,-.82,.82,-1.25,1.25,-1.72,1.72,-2.35,2.35,Math.PI],step=Math.max(12,Math.hypot(dx,dy));let best=null,bestScore=-Infinity;for(const turn of turns){const a=base+turn,ux=Math.cos(a),uy=Math.sin(a),nx=clamp(e.x+ux*step,world.w),ny=clamp(e.y+uy*step,world.h);if(pathBlocked(e.x,e.y,nx,ny,r))continue;let open=0;for(const ahead of [24,52])if(!collidesTree(clamp(nx+ux*ahead,world.w),clamp(ny+uy*ahead,world.h),r))open++;const score=Math.cos(turn)+open*.13+(e.routeAngle==null?0:Math.cos(a-e.routeAngle)*.16);if(score>bestScore){bestScore=score;best={x:nx,y:ny,angle:a}}}if(!best){e.stuck=(e.stuck||0)+1;if(e.stuck>20){const obstacle=trees.reduce((a,t)=>!a||Math.hypot(t.x-e.x,t.y-e.y)<Math.hypot(a.x-e.x,a.y-e.y)?t:a,null);if(obstacle){const away=Math.atan2(e.y-obstacle.y,e.x-obstacle.x);for(const turn of [0,.7,-.7,1.4,-1.4,2.1,-2.1,Math.PI]){const a=away+turn,nx=clamp(obstacle.x+Math.cos(a)*((obstacle.radius||obstacle.s)+r+10),world.w),ny=clamp(obstacle.y+Math.sin(a)*((obstacle.radius||obstacle.s)+r+10),world.h);if(!collidesTree(nx,ny,r)){e.stuck=0;e.routeAngle=a;return {x:nx,y:ny}}}}}return {x:e.x,y:e.y}}e.stuck=0;e.routeAngle=best.angle;return best}
 let enemyGrid=new Map();function buildEnemyGrid(){enemyGrid.clear();for(const e of enemies){const key=Math.floor(e.x/240)+','+Math.floor(e.y/240),bucket=enemyGrid.get(key)||[];bucket.push(e);enemyGrid.set(key,bucket)}}
 function nearbyEnemies(e,radius){const out=[],gx=Math.floor(e.x/240),gy=Math.floor(e.y/240),reach=Math.ceil(radius/240);for(let x=gx-reach;x<=gx+reach;x++)for(let y=gy-reach;y<=gy+reach;y++)for(const o of enemyGrid.get(x+','+y)||[])if(o!==e&&Math.hypot(o.x-e.x,o.y-e.y)<radius)out.push(o);return out}
 const dropTypes={SHIELD:'SHIELD',MEDKIT:'MEDKIT',DOUBLE:'DOUBLE SHOT',RAPID:'RAPID FIRE',TURRET:'CHICKEN TURRET',LASER:'CHICKEN LASER'};const pickupSounds={SHIELD:new Audio('./assets/audio/powerup-shield.mp3'),DOUBLE:new Audio('./assets/audio/powerup-double-shot.mp3'),RAPID:new Audio('./assets/audio/powerup-rapid-fire.mp3'),LASER:new Audio('./assets/audio/powerup-rapid-fire.mp3'),TURRET:new Audio('./assets/audio/powerup-double-shot.mp3')};for(const sound of Object.values(pickupSounds)){sound.preload='auto';sound.volume=.85}function playPickupSound(type){if(!soundOn)return;const sound=pickupSounds[type];if(!sound)return;try{sound.pause();sound.currentTime=0;const playing=sound.play();if(playing?.catch)playing.catch(()=>{})}catch{}}
 const ELITE_NAMES={BOSS:'CHUPACABRAS',MUSHROOM:'MUSHROOM KING',ALIENBOSS:'ALIEN OVERLORD'};
 function startWave(next){wave=next;const base=Math.ceil((6+wave*3+Math.floor(Math.pow(wave,1.35)))*1.5),playerScale=1+Math.max(0,players.size-1)*.25,regular=Math.ceil(base*playerScale),blocks=Math.ceil(regular*4.5/20);spawnGroups=[];tornadoesThisWave=0;for(let i=0;i<blocks;i++)spawnGroups.push(...(Math.random()<.5?[4,4,4,4,4]:[5,5,5,5]));elitesToSpawn=[];if(wave===5)elitesToSpawn.push('BOSS');if(wave>=8)elitesToSpawn.push('MUSHROOM');if(wave>=10)elitesToSpawn.push('ALIENBOSS');remainingToSpawn=spawnGroups.reduce((sum,n)=>sum+n,0)+elitesToSpawn.length;waveGroups=spawnGroups.length;waveElites=elitesToSpawn.length;countdown=3;started=true;spawn=.35;$('#wave').textContent=wave;toast('Wave '+wave+' — prepare!'+(wave>=6?' · a CHICKEN LASER is hidden in this wave':''));tone(520,.16,'triangle');setTimeout(()=>tone(760,.2,'triangle'),140)}
 function chooseEnemyType(){const available=['FOX','WOLF','EAGLE'];if(wave>=2)available.push('SNAKE');if(wave>=3)available.push('MOLE');if(wave>=4)available.push('TORNADO');if(wave>=6)available.push('ALIEN');if(wave>=7)available.push('MAGE');if(wave>=8)available.push('GHOST');if(wave>=9)available.push('PLANT');return available[Math.floor(Math.random()*available.length)]}
 function makeEnemy(type,x,y,p,now){const difficulty=1+(wave-1)*.11,speedScale=1.3*.87*.85;let stats={type,x,y,hitAt:0,phase:Math.random()*6.28,side:Math.random()<.5?-1:1,targetId:null,nextAbility:now+2400+Math.random()*2200,nextFire:now+1800+Math.random()*1000,dashUntil:0,jumpUntil:0,bornAt:now};if(type==='WOLF')Object.assign(stats,{hp:Math.ceil(8*difficulty),speed:34*speedScale,damage:12+Math.floor(p*.45),r:30,icon:'🐺'});else if(type==='EAGLE')Object.assign(stats,{hp:Math.ceil(3*difficulty),speed:85*speedScale,damage:3+Math.floor(p*.18),r:19,icon:'🦅'});else if(type==='SNAKE')Object.assign(stats,{hp:Math.max(1,Math.ceil(2*difficulty)),speed:125*speedScale,damage:3+Math.floor(p*.12),r:17,icon:'🐍'});else if(type==='MOLE')Object.assign(stats,{hp:Math.ceil(5*difficulty),speed:46*speedScale,damage:7+Math.floor(p*.2),r:23,icon:'🐹',burrowUntil:0,emergeAt:now+1700+Math.random()*500,nextAbility:now+4600});else if(type==='TORNADO')Object.assign(stats,{hp:Math.ceil(10*difficulty),speed:240*speedScale,damage:9+Math.floor(p*.3),r:29,icon:'🌪️',launchAt:now+1500,travelAngle:Math.atan2(H.y-y,H.x-x),visualScale:.35});else if(type==='ALIEN')Object.assign(stats,{hp:Math.ceil(5*difficulty),speed:27*speedScale,damage:5+Math.floor(p*.2),r:24,icon:'👽'});else if(type==='MAGE')Object.assign(stats,{hp:Math.ceil(6*difficulty),speed:42*speedScale,damage:7+Math.floor(p*.25),r:23,icon:'🧙'});else if(type==='GHOST')Object.assign(stats,{hp:Math.ceil(4*difficulty),speed:52*speedScale,damage:8+Math.floor(p*.25),r:25,icon:'👻'});else if(type==='PLANT')Object.assign(stats,{hp:Math.ceil(10*difficulty),speed:0,damage:5+Math.floor(p*.2),r:27,icon:'🌱'});else if(type==='FOX')Object.assign(stats,{hp:Math.ceil(3*difficulty),speed:53*speedScale,damage:5+Math.floor(p*.25),r:23,icon:'🦊'});stats.damage=(stats.damage||1)*.4;if(type==='TORNADO')stats.damage=2;stats.maxHp=stats.hp;return stats}
 function findHomeSpawn(radius){for(let i=0;i<48;i++){const a=Math.random()*Math.PI*2,r=220+Math.random()*130,x=H.x+Math.cos(a)*r,y=H.y+Math.sin(a)*r;if(x>radius&&y>radius&&x<world.w-radius&&y<world.h-radius&&!collidesTree(x,y,radius))return {x,y}}return findSpawnPosition(radius)}
 function makeElite(type,x,y,p,now){const speed=27*1.3*.87*.85,base={x,y,type,elite:true,name:ELITE_NAMES[type],hitAt:0,phase:Math.random()*6.28,side:1,targetId:null,nextAbility:now+2600,nextFire:now+1500,dashUntil:0,jumpUntil:0,bornAt:now};
  if(type==='MUSHROOM'){const hp=Math.ceil(190*(1+p*.1));return Object.assign(base,{hp,maxHp:hp,speed:speed*.82,damage:(22+Math.floor(p*.6))*.4,r:44,icon:'🍄',nextAbility:now+3200})}
  if(type==='ALIENBOSS'){const hp=Math.ceil(165*(1+p*.1));return Object.assign(base,{hp,maxHp:hp,speed:speed*1.1,damage:(18+Math.floor(p*.5))*.4,r:40,icon:'👽',nextAbility:now+5200,nextFire:now+2200})}
  const hp=Math.ceil(115*(1+p*.11));return Object.assign(base,{type:'BOSS',hp,maxHp:hp,speed,damage:(24+Math.floor(p*.7))*.4,r:46,icon:'👹',nextAbility:now+2200,nextFire:now+1300})}
 function spawnElite(type,now){const p=wave-1,{x,y}=findSpawnPosition(46),e=makeElite(type,x,y,p,now);if(type==='BOSS'&&wave===5&&!turret.active)e.turretDrop=true;enemies.push(e);pushFx('eliteSpawn',x,y,{type});toast(e.name+' ELITE INCOMING!');tone(type==='MUSHROOM'?70:type==='ALIENBOSS'?160:95,.55,'sawtooth',.065)}
 function spawnEnemy(){const p=wave-1,now=clock();if(elitesToSpawn.length&&(waveGroups-spawnGroups.length)>=waveGroups*(waveElites-elitesToSpawn.length+1)/(waveElites+1)){spawnElite(elitesToSpawn.shift(),now);remainingToSpawn--;return}if(wave>=6&&Math.random()<.08&&!enemies.some(e=>e.type==='BOSS'))spawnElite('BOSS',now);let amount=spawnGroups.shift()||Math.min(4,remainingToSpawn-elitesToSpawn.length);if(amount<=0)return;const type=chooseEnemyType(),tornadoCount=type==='TORNADO'?Math.min(amount,2-tornadoesThisWave):0;if(tornadoCount)tornadoesThisWave+=tornadoCount;const center=(type==='MOLE'||type==='PLANT')?findHomeSpawn(type==='PLANT'?34:26):findSpawnPosition(28),{x,y}=center;for(let i=0;i<amount;i++){const enemyType=type==='TORNADO'&&i>=tornadoCount?'FOX':type,angle=i/amount*Math.PI*2+Math.random()*.3,offset=i===0?0:58+Math.random()*46;let ex=x+Math.cos(angle)*offset,ey=y+Math.sin(angle)*offset,stats=makeEnemy(enemyType,ex,ey,p,now);if(i>0&&collidesTree(ex,ey,stats.r)){const spot=(enemyType==='MOLE'||enemyType==='PLANT')?findHomeSpawn(stats.r):findSpawnPosition(stats.r);stats.x=spot.x;stats.y=spot.y}enemies.push(stats)}remainingToSpawn-=amount}
 function aimTarget(e){let best=null,bestD=780;for(const p of players.values()){if(p.hp<=0)continue;const d=Math.hypot(p.x-e.x,p.y-e.y);if(d<bestD){best=p;bestD=d}}const homeD=Math.hypot(H.x-e.x,H.y-e.y);return best&&bestD<homeD+240?{obj:best,type:'player'}:{obj:H,type:'farm'}}
 function pushDrop(x,y,type,life){drops.push({id:++dropId,x,y,type,label:dropTypes[type],life,maxLife:life,bornAt:clock()})}
 // Laser: at most ONE per wave from wave 6. Small chance on each kill, guaranteed near the end of the wave.
 function dropPower(x,y,guaranteed=false){if(wave>=6&&laserWave!==wave){const nearEnd=remainingToSpawn===0&&enemies.filter(e=>e.hp>0).length<=4;if(nearEnd||Math.random()<.045){laserWave=wave;pushDrop(x,y,'LASER',40);toast('A CHICKEN LASER dropped!');return}}if(!guaranteed&&Math.random()>.10)return;const roll=Math.random(),type=roll<.40?'SHIELD':roll<.60?'MEDKIT':roll<.85?'DOUBLE':'RAPID';pushDrop(x,y,type,24)}
 function awardKill(e,id){if(e.scored)return;e.scored=true;const p=players.get(id);if(!p)return;const value={FOX:10,WOLF:25,EAGLE:15,SNAKE:12,MOLE:12,TORNADO:22,ALIEN:22,MAGE:24,GHOST:18,PLANT:20,BOSS:100,MUSHROOM:150,ALIENBOSS:175}[e.type]||10;p.kills++;p.score+=value}
 function damagePlayer(target,damage,now){if(target.hp<=0)return;if(now<(target.effects.SHIELD||0))return send(target);target.hp=Math.max(0,target.hp-damage);target.lastHit=now;if(target.hp===0){target.deathAt=now;target.revive=0;if(target.effects.LASER){delete target.effects.LASER;toast(target.name+' was knocked out and lost the CHICKEN LASER')}chickDeathSound();pushFx('down',target.x,target.y,{playerId:target.id})}tone(115,.085,'square',.035);send(target,true)}
 function damageFarm(damage,now){if(godMode)damage=0;farmHp=Math.max(0,farmHp-damage);henLastHit=now;if(now-lastHenCry>700){lastHenCry=now;henCry()}}
 function applyEnemyDamage(choice,damage,now){if(choice.type==='player')damagePlayer(choice.obj,damage,now);else damageFarm(damage,now)}
 function hittable(e,now){return e.hp>0&&!(e.type==='MOLE'&&(now<e.burrowUntil||now<(e.emergeAt||0)))&&!(e.type==='ALIENBOSS'&&now<(e.blinkUntil||0))}
 function hitEnemy(e,damage,ownerId,now){e.hp-=damage;e.lastHitBy=ownerId;e.hitUntil=now+100;if(e.hp<=0){bloodSplats.push({x:e.x,y:e.y,life:7,size:12+Math.random()*8,seed:Math.random()*1000,elite:!!e.elite});awardKill(e,ownerId);if(e.turretDrop&&!turret.active&&!drops.some(d=>d.type==='TURRET')){pushDrop(e.x,e.y,'TURRET',Infinity);toast('The Chupacabras dropped a CHICKEN TURRET! Grab it!')}else dropPower(e.x,e.y,!!e.elite);if(e.elite)pushFx('eliteDeath',e.x,e.y,{type:e.type});tone(125,.14,'sawtooth',.05);setTimeout(()=>tone(70,.2,'triangle',.04),45)}else tone(210,.035,'triangle',.012)}
 function beamHitsPoint(x1,y1,x2,y2,px,py,r){const vx=x2-x1,vy=y2-y1,l2=vx*vx+vy*vy||1,t=Math.max(0,Math.min(1,((px-x1)*vx+(py-y1)*vy)/l2));return Math.hypot(x1+vx*t-px,y1+vy*t-py)<r}
 function beamLength(x,y,a,max){for(let step=24;step<max;step+=12)if(collidesTree(x+Math.cos(a)*step,y+Math.sin(a)*step,4,true))return step;return max}
 function updateEnemy(e,dt,now){if(e.type==='MOLE'&&now<(e.emergeAt||0))return;if(e.type==='TORNADO'){if(now<e.launchAt){e.visualScale=.35+.8*Math.min(1,(now-e.bornAt)/1500);return}e.visualScale=1.2;e.x+=Math.cos(e.travelAngle)*e.speed*dt;e.y+=Math.sin(e.travelAngle)*e.speed*dt;if(now-e.hitAt>850){for(const p of players.values())if(p.hp>0&&Math.hypot(p.x-e.x,p.y-e.y)<e.r+27){e.hitAt=now;applyEnemyDamage({obj:p,type:'player'},e.damage,now);break}if(now-e.hitAt>850&&Math.hypot(H.x-e.x,H.y-e.y)<e.r+65){e.hitAt=now;applyEnemyDamage({obj:H,type:'farm'},e.damage,now)}}if(e.x< -100||e.y< -100||e.x>world.w+100||e.y>world.h+100)e.hp=0;return}let choice=aimTarget(e);const pack=nearbyEnemies(e,240);if(e.type==='WOLF'){const focused=pack.find(o=>o.type==='WOLF'&&o.targetId&&players.has(o.targetId));if(focused){const p=players.get(focused.targetId);if(p&&p.hp>0)choice={obj:p,type:'player'}}}
  let target=choice.obj,dx=target.x-e.x,dy=target.y-e.y,d=Math.hypot(dx,dy)||1;e.targetId=choice.type==='player'?target.id:null;e.facing=Math.atan2(dy,dx);let vx=dx/d,vy=dy/d;
  if(e.type==='BOSS'&&d<760&&now>=(e.nextFire||0)){e.nextFire=now+2600;e.attackAt=now;const angle=Math.atan2(dy,dx),speed=310;fireballs.push({x:e.x+Math.cos(angle)*32,y:e.y+Math.sin(angle)*32,dx:Math.cos(angle)*speed,dy:Math.sin(angle)*speed,t:3.2,damage:5.6,kind:'fire'});tone(145,.24,'sawtooth',.045)}
  if(e.type==='MUSHROOM'&&now>=e.nextAbility){e.nextAbility=now+4600;e.attackAt=now;const n=12;for(let i=0;i<n;i++){const a=i/n*Math.PI*2+e.phase,speed=200;fireballs.push({x:e.x+Math.cos(a)*36,y:e.y+Math.sin(a)*36,dx:Math.cos(a)*speed,dy:Math.sin(a)*speed,t:2.6,damage:4,kind:'spore'})}pushFx('sporeBurst',e.x,e.y);sweep(180,60,.45,'triangle',.06)}
  if(e.type==='ALIENBOSS'){if(d<720&&now>=e.nextFire){e.nextFire=now+3100;e.attackAt=now;for(const off of [-.24,0,.24]){const a=Math.atan2(dy,dx)+off,len=beamLength(e.x,e.y,a,Math.min(640,d+120)),x2=e.x+Math.cos(a)*len,y2=e.y+Math.sin(a)*len;enemyBeams.push({x1:e.x+Math.cos(a)*30,y1:e.y+Math.sin(a)*30,x2,y2,t:.4,color:'#c46bff',width:2});for(const p of players.values())if(p.hp>0&&beamHitsPoint(e.x,e.y,x2,y2,p.x,p.y,28))damagePlayer(p,6,now);if(off===0&&choice.type==='farm'&&len>=d-70)damageFarm(6,now)}sweep(900,300,.3,'sawtooth',.04)}if(now>=e.nextAbility&&d>220){e.nextAbility=now+6200+Math.random()*1800;const angle=Math.random()*Math.PI*2,tx=Math.max(80,Math.min(world.w-80,target.x+Math.cos(angle)*230)),ty=Math.max(80,Math.min(world.h-80,target.y+Math.sin(angle)*230));if(!collidesTree(tx,ty,e.r)){pushFx('teleport',e.x,e.y,{to:{x:tx,y:ty},color:'#c46bff'});e.x=tx;e.y=ty;e.blinkUntil=now+260;e.teleportAt=now;sweep(300,1400,.25,'sine',.04)}}}
  if(e.type==='ALIEN'&&d<670&&now>=e.nextFire){e.nextFire=now+3000;let length=d,blocked=false;for(let step=24;step<d;step+=20)if(collidesTree(e.x+vx*step,e.y+vy*step,5,true)){length=step;blocked=true;break}enemyBeams.push({x1:e.x+vx*20,y1:e.y+vy*20,x2:e.x+vx*length,y2:e.y+vy*length,t:.24,color:'#7cfff0'});if(!blocked)applyEnemyDamage(choice,e.damage*1.5,now);tone(780,.12,'sawtooth',.035)}
  if(e.type==='PLANT'&&d<650&&now>=e.nextFire){e.nextFire=now+1950;e.attackAt=now;const angle=Math.atan2(dy,dx),speed=260;fireballs.push({x:e.x+Math.cos(angle)*28,y:e.y+Math.sin(angle)*28,dx:Math.cos(angle)*speed,dy:Math.sin(angle)*speed,t:3.1,damage:e.damage,kind:'seed'});tone(360,.07,'triangle',.025)}
  if(e.type==='MAGE'&&d>230&&now>=e.nextAbility){e.nextAbility=now+4200+Math.random()*1000;const angle=Math.random()*Math.PI*2,tx=Math.max(70,Math.min(world.w-70,target.x+Math.cos(angle)*190)),ty=Math.max(70,Math.min(world.h-70,target.y+Math.sin(angle)*190));if(!collidesTree(tx,ty,e.r)){pushFx('teleport',e.x,e.y,{to:{x:tx,y:ty},color:'#9d6bff'});e.x=tx;e.y=ty;e.teleportUntil=now+450;e.teleportAt=now;sweep(380,1500,.22,'sine',.04)}}
  if(e.type==='MOLE'&&now>=e.nextAbility){e.nextAbility=now+5100;e.burrowUntil=now+900}
  const nearby=pack.filter(o=>Math.hypot(o.x-e.x,o.y-e.y)<150).length,flank=Math.sin(now/430+e.phase)*(.16+Math.min(.5,nearby*.08))*e.side;vx+=(-dy/d)*flank;vy+=(dx/d)*flank;
  if(e.type==='FOX'&&now>e.nextAbility&&d>145){e.nextAbility=now+3800+Math.random()*3000;e.dashUntil=now+360;e.jumpUntil=e.dashUntil}if(e.type==='EAGLE'&&now>e.nextAbility&&d>140){e.nextAbility=now+4200+Math.random()*2400;e.dashUntil=now+850;e.dashX=target.x;e.dashY=target.y}
  let speed=e.speed;if(e.type==='FOX'&&now<e.dashUntil)speed*=2.55;if(e.type==='EAGLE'&&now<e.dashUntil){const ddx=e.dashX-e.x,ddy=e.dashY-e.y,dd=Math.hypot(ddx,ddy)||1;vx=ddx/dd;vy=ddy/dd;speed*=2.8}
  if(e.type==='PLANT')return;if(d>e.r+31&&speed>0){const dxm=vx/Math.hypot(vx,vy)*speed*dt,dym=vy/Math.hypot(vx,vy)*speed*dt;const oldX=e.x,oldY=e.y;let pos;if(e.type==='GHOST'||e.type==='EAGLE'||(e.type==='MOLE'&&now<e.burrowUntil)){pos={x:Math.max(e.r,Math.min(world.w-e.r,e.x+dxm)),y:Math.max(e.r,Math.min(world.h-e.r,e.y+dym))}}else pos=moveEnemy(e,dxm,dym,e.r);e.x=pos.x;e.y=pos.y;const moved=Math.hypot(e.x-oldX,e.y-oldY);e.moving=moved>.01;if(e.moving)e.facing=Math.atan2(e.y-oldY,e.x-oldX)}
  else{e.moving=false;if(now-e.hitAt>780){e.hitAt=now;e.attackAt=now;applyEnemyDamage(choice,e.damage,now)}}
 }
 function makeShot(p,angle){const dx=Math.cos(angle),dy=Math.sin(angle);shots.push({x:p.x+dx*34,y:p.y+dy*34,dx:dx*620,dy:dy*620,t:1.1,damage:1,ownerId:p.id,color:p.color})}
 // Chicken laser: short-range hitscan beam, double damage, blocked only by trees/rocks.
 const LASER_RANGE=250;function fireLaser(p,angle,now){const x0=p.x+Math.cos(angle)*30,y0=p.y+Math.sin(angle)*30;let len=beamLength(x0,y0,angle,LASER_RANGE),hit=null;for(let s=0;s<=len;s+=10){const x=x0+Math.cos(angle)*s,y=y0+Math.sin(angle)*s;for(const e of enemies)if(hittable(e,now)&&Math.hypot(e.x-x,e.y-y)<e.r+6){hit=e;break}if(hit){len=s;break}}if(hit)hitEnemy(hit,2,p.id,now);(p.beams=p.beams||[]).push({a:angle,len,until:now+110,hit:!!hit})}
 function updateTurret(dt,now){if(!turret.active)return;let best=null,bestD=600;for(const e of enemies){if(!hittable(e,now))continue;const d=Math.hypot(e.x-H.x,e.y-H.y);if(d<bestD){best=e;bestD=d}}if(!best){turret.target=null;return}turret.target=best;const desired=Math.atan2(best.y-H.y,best.x-H.x);let diff=Math.atan2(Math.sin(desired-turret.angle),Math.cos(desired-turret.angle));turret.angle+=Math.max(-7*dt,Math.min(7*dt,diff));if(Math.abs(diff)<.25&&now-turret.lastShot>120){turret.lastShot=now;turret.shotAt=now;const a=turret.angle,dx=Math.cos(a),dy=Math.sin(a);shots.push({x:H.x+dx*30,y:H.y+dy*30,dx:dx*680,dy:dy*680,t:1.0,damage:1,ownerId:'TURRET',turret:true,startX:H.x,startY:H.y,color:'#ffd34d'})}}
 function updateRevives(dt,now){for(const p of players.values()){if(p.hp>0||!p.connected){p.revive=0;p.revivers=0;continue}let helpers=0;for(const o of players.values())if(o!==p&&o.hp>0&&o.connected&&Math.hypot(o.x-p.x,o.y-p.y)<52)helpers++;p.revivers=helpers;if(!helpers){if(p.revive>0)p.revive=0;continue}p.revive=(p.revive||0)+dt;if(Math.floor((p.revive-dt)*2)<Math.floor(p.revive*2))tone(500+p.revive*120,.06,'sine',.02);if(p.revive>=5){p.hp=60;p.deathAt=0;p.revive=0;p.lastHit=0;p.effects.SHIELD=now+2500;for(const o of players.values())if(o!==p&&o.hp>0&&Math.hypot(o.x-p.x,o.y-p.y)<52)o.score+=30;pushFx('revive',p.x,p.y,{playerId:p.id});toast(p.name+' is back in the fight!');sweep(500,1300,.45,'triangle',.06);send(p,true)}}}
 function tick(dt,now){if(!started||paused)return;if(countdown>0){const before=Math.ceil(countdown);countdown=Math.max(0,countdown-dt);if(countdown>0&&Math.ceil(countdown)<before)tone(440+before*75,.08,'square',.025);if(countdown===0)spawn=.35}if(countdown===0){spawn-=dt;if(remainingToSpawn>0&&spawn<=0){spawn=Math.max(.32,1.7-wave*.055);spawnEnemy()}}buildEnemyGrid();for(const e of enemies)updateEnemy(e,dt,now);
  for(const p of players.values()){if(p.beams)p.beams=p.beams.filter(b=>b.until>now);if(p.connected&&now-(p.lastSeen||now)>12000){try{p.conn?.close()}catch{}}if(p.hp<=0||!p.connected){send(p);continue}const ox=p.x,oy=p.y,pos=moveCircle(p,p.move.x*207*dt,p.move.y*207*dt,25);p.x=pos.x;p.y=pos.y;p.speed=Math.hypot(p.x-ox,p.y-oy)/Math.max(dt,.001);
   const rapid=!!p.effects.RAPID,double=!!p.effects.DOUBLE,laser=!!p.effects.LASER;if(p.fire&&now-(p.lastShot||0)>(rapid?65:120)){p.lastShot=now;const angles=double?[p.aim-.13,p.aim+.13]:[p.aim];for(const a of angles)laser?fireLaser(p,a,now):makeShot(p,a)}
   for(const d of drops){if(!d.taken&&Math.hypot(d.x-p.x,d.y-p.y)<46){d.taken=true;pushFx('pickup',d.x,d.y,{type:d.type,playerId:p.id});if(d.type==='MEDKIT'){p.hp=Math.min(100,p.hp+35);toast(p.name+' picked up a medkit')}else if(d.type==='SHIELD'){p.effects.SHIELD=now+26000;toast(p.name+' picked up a shield')}else if(d.type==='DOUBLE'){const already=p.effects.DOUBLE;p.effects.DOUBLE=true;toast(already?'Double shot already unlocked':p.name+' unlocked permanent double shot')}else if(d.type==='RAPID'){const already=p.effects.RAPID;p.effects.RAPID=true;toast(already?'Rapid fire already unlocked':p.name+' unlocked permanent rapid fire')}else if(d.type==='LASER'){p.effects.LASER=true;toast(p.name+' equipped the CHICKEN LASER — short range, double damage!')}else if(d.type==='TURRET'){turret.active=true;toast(p.name+' deployed the CHICKEN TURRET on the farm!');pushFx('turretDeploy',H.x,H.y)}playPickupSound(d.type)}}send(p)}
  updateRevives(dt,now);updateTurret(dt,now);
  for(const b of shots){const ox=b.x,oy=b.y;b.x+=b.dx*dt;b.y+=b.dy*dt;b.t-=dt;if(!b.turret&&pathBlocked(ox,oy,b.x,b.y,5,true)){b.t=0;continue}for(const e of enemies){if(hittable(e,now)&&Math.hypot(e.x-b.x,e.y-b.y)<e.r+5){hitEnemy(e,b.damage,b.ownerId,now);b.t=0;break}}}if(soundOn&&shots.length&&now-lastShotSound>220){tone(320,.045,'square',.018);lastShotSound=now}
  for(const b of fireballs){const ox=b.x,oy=b.y;b.x+=b.dx*dt;b.y+=b.dy*dt;b.t-=dt;if(b.x<0||b.y<0||b.x>world.w||b.y>world.h||pathBlocked(ox,oy,b.x,b.y,10,true)){b.t=0;continue}let hit=false;for(const p of players.values())if(p.hp>0&&Math.hypot(p.x-b.x,p.y-b.y)<32){damagePlayer(p,b.damage,now);hit=true;break}if(!hit&&Math.hypot(H.x-b.x,H.y-b.y)<125){damageFarm(b.damage,now);hit=true}if(hit)b.t=0}fireballs=fireballs.filter(b=>b.t>0);
  shots=shots.filter(b=>b.t>0);bloodSplats=bloodSplats.filter(s=>(s.life-=dt)>0);enemyBeams=enemyBeams.filter(b=>((b.t-=dt)>0));enemies=enemies.filter(e=>e.hp>0);drops=drops.filter(d=>!d.taken&&((d.life-=dt)>0));fx=fx.filter(f=>now-f.at<4000);if(farmHp<=0&&!gameOver){started=false;gameOver=true;countdown=0;saveRun();for(const p of players.values()){if(p.hp>0){p.hp=0;p.deathAt=now}try{if(p.conn?.open)p.conn.send({type:'gameOver',started:false})}catch{}send(p,true)}$('#startBtn').disabled=false}else if(remainingToSpawn===0&&enemies.length===0&&wave>0&&countdown===0){farmHp=Math.min(100,farmHp+8);startWave(wave+1)}$('#farmHp').textContent=Math.ceil(farmHp)+'%';$('#enemyCount').textContent=remainingToSpawn+enemies.length;
 }
 function draw(frameTime){const dt=Math.min(.05,(frameTime-last)/1000);last=frameTime;const now=clock();tick(dt,now);if(!started)for(const p of players.values())send(p);game3d.render({players,enemies,shots,fireballs,drops,enemyBeams,bloodSplats,farmHp,henLastHit,countdown,wave,turret,fx,lobby:!started&&!gameOver,gameOver},dt,now);$('#wave').textContent=wave;const cd=$('#countdown');if(cd){const show=countdown>0&&started;cd.classList.toggle('show',show);if(show){const v=Math.ceil(countdown);if(cd.dataset.v!==wave+':'+v){cd.dataset.v=wave+':'+v;cd.innerHTML=`<small>WAVE ${wave} · GET READY</small><b>${v}</b>`+(wave===5?'<em>CHUPACABRAS WAVE · it drops the CHICKEN TURRET</em>':wave>=8&&wave<10?'<em>MUSHROOM KING ELITE INCOMING</em>':wave>=10?'<em>MUSHROOM KING + ALIEN OVERLORD INCOMING</em>':wave>=6?'<em>1 CHICKEN LASER hidden in this wave</em>':'')}}}requestAnimationFrame(draw);}
 requestAnimationFrame(draw);
 window.__chickenHorde={players,get enemies(){return enemies},get drops(){return drops},turret,world,trees,startMatch,setWave:n=>{enemies=[];startWave(n)},spawnElite:t=>spawnElite(t,clock()),pushDrop:(t,x=H.x,y=H.y+140)=>pushDrop(x,y,t,60),get farmHp(){return farmHp},set farmHp(v){farmHp=v},hitFarm:()=>damageFarm(0,clock()),get roomCode(){return roomCode},net,pause:v=>{paused=v},god:v=>{godMode=v},addEnemy:(type,x,y,extra={})=>{const now=clock(),e=['BOSS','MUSHROOM','ALIENBOSS'].includes(type)?makeElite(type,x,y,wave,now):makeEnemy(type,x,y,wave,now);Object.assign(e,extra);enemies.push(e);return e},get laserWave(){return laserWave},dbg:()=>({wave,started,paused,countdown,remainingToSpawn,elitesToSpawn,waveGroups,left:spawnGroups.length,n:enemies.length,farmHp,gameOver}),hit:(e,d,id)=>hitEnemy(e,d,id,clock()),sim:sec=>{for(let t=0;t<sec;t+=.05){timeShift+=50;for(const p of players.values())if(p.connected)p.lastSeen=clock();tick(.05,clock())}return enemies.length},addBot:name=>{const c=new Emitter();c.open=true;c.send=()=>{};c.close=()=>{c.open=false;c.emit('close')};onIncoming(c);c.emit('data',{type:'join',clientId:'bot-'+name,name});return c}};
}

function lockMobileZoom(){
 // iOS Safari ignores user-scalable=no, so block pinch, double-tap and gesture zoom explicitly while keeping text inputs usable.
 const isField=t=>!!t&&!!t.closest&&!!t.closest('input,textarea,select,label');
 for(const type of ['gesturestart','gesturechange','gestureend'])document.addEventListener(type,e=>e.preventDefault(),{passive:false});
 document.addEventListener('touchmove',e=>{if(e.touches.length>1||!isField(e.target))e.preventDefault()},{passive:false});
 document.addEventListener('touchstart',e=>{if(e.touches.length>1)e.preventDefault()},{passive:false});
 let lastTouchEnd=0;document.addEventListener('touchend',e=>{const now=Date.now();if(now-lastTouchEnd<380&&!isField(e.target))e.preventDefault();lastTouchEnd=now},{passive:false});
 document.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});
 document.addEventListener('contextmenu',e=>{if(!isField(e.target))e.preventDefault()});
 // If iOS already zoomed (e.g. while the keyboard was open), snap the viewport back when the field loses focus.
 const vp=document.querySelector('meta[name=viewport]');document.addEventListener('focusout',()=>{if(!vp)return;const c=vp.content;vp.content=c+',width=device-width';setTimeout(()=>{vp.content=c;scrollTo(0,0)},60)});
}
function initController(roomId){
 lockMobileZoom();
 const status=$('#joinStatus'),connStatus=$('#connection');let peer=null,conn=null,relayWs=null,move={x:0,y:0},aim=0,fire=false,joined=false,attempt=0;
 let wasKicked=false;const clientKey='chicken-horde-client-id';let clientId;try{clientId=localStorage.getItem(clientKey);if(!clientId){clientId=crypto.randomUUID?.()||('c'+Math.random().toString(36).slice(2));localStorage.setItem(clientKey,clientId)}}catch{clientId='c'+Math.random().toString(36).slice(2)}let savedName='';try{savedName=localStorage.getItem('chicken-horde-player-name')||''}catch{}if(savedName)$('#playerName').value=savedName;let retryDelay=1000,retryTimer=null;
 const prefKey='chicken-horde-transport',getPref=()=>{try{return sessionStorage.getItem(prefKey)}catch{return null}},hasRelay=()=>!!relayUrl();
 function currentName(){let name=$('#playerName').value.trim()||'CHICK';try{name=localStorage.getItem('chicken-horde-player-name')||name}catch{}return name}
 function useConn(c,kind){if(conn&&conn.open&&conn!==c){try{c.close()}catch{}return}conn=c;retryDelay=1000;clearTimeout(retryTimer);connStatus.textContent='CONNECTED · '+(kind==='relay'?'RELAY':'P2P');try{sessionStorage.setItem(prefKey,kind)}catch{}status.textContent=joined?'Reconnected. Welcome back!':'Connected to the farm.';$('#joinBtn').disabled=false;if(joined)c.send({type:'join',clientId,name:currentName()})}
 function onData(c,d){if(c!==conn||!d)return;if(d.type==='kicked'){wasKicked=true;joined=false;$('#joinPanel').classList.remove('hidden');$('#controls').classList.add('hidden');status.textContent='The host removed you from the lobby.';connStatus.textContent='REMOVED'}else if(d.type==='state'&&joined)updateBadge(d);else if(d.type==='gameOver')updateBadge({hp:0,started:false,over:true})}
 function onClose(c){if(c!==conn)return;conn=null;if(wasKicked)return;connStatus.textContent='RECONNECTING';status.textContent='Connection lost; trying to reconnect…';schedule()}
 function schedule(){clearTimeout(retryTimer);retryTimer=setTimeout(tryConnect,retryDelay);retryDelay=Math.min(8000,retryDelay*1.6)}
 function tryConnect(){if(wasKicked||(conn&&conn.open))return;const id=++attempt,p2pOk=typeof Peer!=='undefined';if(hasRelay()&&(getPref()==='relay'||!p2pOk))connectRelay();else{connectP2P();if(hasRelay())setTimeout(()=>{if(id===attempt&&!(conn&&conn.open)){status.textContent='P2P is slow or blocked — switching to relay…';connectRelay()}},CFG.p2pTimeout)}setTimeout(()=>{if(id===attempt&&!(conn&&conn.open))schedule()},CFG.p2pTimeout+7000)}
 function ensurePeer(cb){if(typeof Peer==='undefined')return;if(peer&&!peer.destroyed&&peer.open)return cb();if(peer&&!peer.destroyed){peer.__wait=cb;if(peer.disconnected)try{peer.reconnect()}catch{}return}peer=new Peer(undefined,peerOptions());peer.__wait=cb;peer.on('open',()=>{const f=peer.__wait;peer.__wait=null;f?.()});peer.on('disconnected',()=>{setTimeout(()=>{try{if(peer&&!peer.destroyed)peer.reconnect()}catch{}},1000)});peer.on('error',e=>{if(e.type==='peer-unavailable')status.textContent='Room '+roomId+' not found over P2P — check the code or wait for the host.';else if(['network','server-error','socket-error','socket-closed'].includes(e.type)&&hasRelay())connectRelay();else status.textContent='Trying to reach the host ('+e.type+')'})}
 function connectP2P(){ensurePeer(()=>{try{const c=peer.connect(CFG.peerPrefix+roomId,{reliable:true});c.on('open',()=>useConn(c,'p2p'));c.on('data',d=>onData(c,d));c.on('close',()=>onClose(c));c.on('error',()=>{})}catch{}})}
 function connectRelay(){const url=relayUrl();if(!url||(relayWs&&relayWs.readyState<=1))return;let ws;try{ws=new WebSocket(url)}catch{return}relayWs=ws;const c=new Emitter();c.open=false;c.send=d=>{if(ws.readyState===1)ws.send(JSON.stringify({t:'d',d}))};c.close=()=>{c.open=false;try{ws.close()}catch{}};ws.onopen=()=>ws.send(JSON.stringify({t:'join',room:roomId}));ws.onmessage=ev=>{let m;try{m=JSON.parse(ev.data)}catch{return}if(m.t==='joined'){c.open=true;useConn(c,'relay')}else if(m.t==='d')onData(c,m.d);else if(m.t==='rejoin'){if(joined&&c===conn)c.send({type:'join',clientId,name:currentName()})}else if(m.t==='error')status.textContent=m.reason==='no-room'?'Room '+roomId+' is not open on the relay yet — waiting for the host…':'Relay: '+m.reason};ws.onclose=()=>{const was=c.open;c.open=false;if(relayWs===ws)relayWs=null;if(was)onClose(c)};ws.onerror=()=>{}}
 connStatus.textContent='CONNECTING';tryConnect();
 // Player badge: shows the chick colour picked by the host, health and the revive progress.
 function updateBadge(d){const badge=$('#meBadge');if(!badge)return;badge.classList.remove('hidden');if(d.color){badge.style.setProperty('--chick',d.color);document.documentElement.style.setProperty('--chick',d.color)}if(d.name)$('#meName').textContent=d.name;const down=d.hp<=0&&d.started;badge.classList.toggle('down',!!down);$('#meHp').style.width=Math.max(0,Math.min(100,d.hp||0))+'%';$('#meState').textContent=d.over?'GAME OVER — back to lobby soon':down?(d.revive>0?`REVIVING… ${Math.round(d.revive/5*100)}%`:'DOWN! A teammate must stand under you for 5 s'):d.started?(d.laser?'⚡ CHICKEN LASER EQUIPPED':'Defend Mama Hen!'):'In the lobby — waiting for the host';status.textContent=d.started?'Defend the farm!':status.textContent}
 $('#playerName').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#playerName').blur();$('#joinBtn').click()}});
 $('#joinBtn').onclick=()=>{if(!conn||!conn.open){status.textContent='Still connecting to the host…';return}const name=$('#playerName').value.trim()||'CHICK';try{localStorage.setItem('chicken-horde-player-name',name)}catch{}conn.send({type:'join',clientId,name});joined=true;$('#playerName').blur();$('#joinPanel').classList.add('hidden');$('#controls').classList.remove('hidden');updateBadge({name,hp:100,started:false})};
 function setupStick(zone,kind){const base=zone.querySelector('.stick-base'),knob=zone.querySelector('.stick-knob');let pointer=null;function set(e){const r=base.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),limit=r.width*.34,d=Math.hypot(dx,dy),k=d>limit?limit/d:1,nx=dx*k,ny=dy*k;knob.style.transform=`translate(${nx}px,${ny}px)`;const mag=Math.hypot(nx,ny)/limit,dead=.16;if(kind==='move'){if(mag<dead)move={x:0,y:0};else{const q=(mag-dead)/(1-dead);move={x:nx/d*q,y:ny/d*q}}}else{if(mag>=dead)aim=Math.atan2(ny,nx);fire=mag>=dead}}
  zone.addEventListener('pointerdown',e=>{if(pointer!==null)return;pointer=e.pointerId;try{zone.setPointerCapture(pointer)}catch{}set(e);e.preventDefault()});zone.addEventListener('pointermove',e=>{if(e.pointerId===pointer){set(e);e.preventDefault()}});function up(e){if(e.pointerId!==pointer)return;pointer=null;knob.style.transform='translate(0,0)';if(kind==='move')move={x:0,y:0};else fire=false}zone.addEventListener('pointerup',up);zone.addEventListener('pointercancel',up);zone.addEventListener('lostpointercapture',up);zone.addEventListener('touchstart',e=>e.preventDefault(),{passive:false})}
 setupStick($('#moveZone'),'move');setupStick($('#aimZone'),'aim');
 const fireBtn=$('#fire');fireBtn.classList.add('hidden');
 // iPhone fix: never swallow keystrokes while the player types a name (A, D, W, S and space were being blocked).
 const typing=e=>{const t=e.target;return !!t&&(t.tagName==='INPUT'||t.tagName==='TEXTAREA'||t.isContentEditable)};
 const keys=new Set();addEventListener('keydown',e=>{if(typing(e)||!joined)return;const k=(e.key||'').toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.add(k);if(k===' ')fire=true});addEventListener('keyup',e=>{if(typing(e))return;const k=(e.key||'').toLowerCase();keys.delete(k);if(k===' ')fire=false});addEventListener('blur',()=>{keys.clear();fire=false});addEventListener('mousemove',e=>{if(joined&&e.pointerType!=='touch')aim=Math.atan2(e.clientY-innerHeight/2,e.clientX-innerWidth/2)});addEventListener('mousedown',e=>{if(joined&&e.button===0&&!e.target.closest?.('.stick-zone,button,input'))fire=true});addEventListener('mouseup',e=>{if(e.button===0&&!e.target.closest?.('.stick-zone'))fire=false});
 let lastPing=0;setInterval(()=>{const x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0),m=Math.hypot(x,y);if(m)move={x:x/m,y:y/m};if(conn?.open&&joined)conn.send({type:'input',move:{x:+move.x.toFixed(3),y:+move.y.toFixed(3)},aim:+aim.toFixed(3),fire});else if(conn?.open&&Date.now()-lastPing>4000){lastPing=Date.now();conn.send({type:'ping'})}},50);
}
})();
